#pragma once

//this is the main hub the radio station for the transmittion and the collection of all the events 
//there is a queue of the events that collects all the events that are generated by all the systems
//then there is a lamba collection of systems that will resolve this events 

#include<functional>
#include<vector>
#include<memory>
#include"event.h"
#include<unordered_map>

class eventBus
{
private:
	std::unordered_map < eventTypes, std::vector<std::function<void(event*)>>> m_subscribers;
	std::vector<event*> m_eventQueue;
public:
	eventBus() {}

	void subscribe( eventTypes typeOfEvent, std::function<void(event*)> funct) {
		m_subscribers[typeOfEvent].push_back(funct);
	}

	void publishEvent(eventTypes type, event* event) {

	}
};

