#pragma once

//this is the main hub the radio station for the transmittion and the collection of all the events 
//there is a queue of the events that collects all the events that are generated by all the systems
//then there is a lamba collection of systems that will resolve this events 

#include<functional>
#include<vector>
#include<memory>
#include"event.h"
#include<unordered_map>

class eventBus
{
private:
	//here the function takes in a type of event* to allow for polymorphic behaviour
	std::unordered_map < eventTypes, std::vector<std::function<void(const event*)>>> m_subscribers;
	std::vector<std::shared_ptr<event>> m_eventQueue;
public:
	eventBus() {}

	//this calls a funtion that is defined by me therefore there are various systems that is hand writted for the resolution of the events , this is the event consumer
	void subscribe( eventTypes typeOfEvent, std::function<void(const event*)> funct) {
		m_subscribers[typeOfEvent].push_back(funct);
	}
	//this funtion is to be called by the systems in the scene to create the events for example the input system may generate the create entity event , this is the event generator
	void publishEvent(std::shared_ptr<event> event) {
		m_eventQueue.push_back(event);
	}
	void resolveEventsFromEventQueue() {
		for (const auto& event : m_eventQueue) {
			for (const auto& subscriberForThisEvent : m_subscribers[event->getEventType()]) {
				subscriberForThisEvent(event.get());
			}
		}
		m_eventQueue.clear();
	}
};

