#pragma once

//what is the event class 
//it is something that is used to generate a fact in the world that is wrapped into
//a class and then passed to other systems to be interpreted

//actions are things that are given to be implemented or something that the user wants to happen in the world
//the event is a fact that has already happened that the system has to interperte and then output the requried changes 
//for that event 

//for example user fire arrow by current player - action
//the arrow is fired (in this this direction this manner ...) - event (since this is going to be a fact)
//this event is then interpreted by the system of spawn arrow entity
//the arrow is spawned
//then when this arrow reaches some enemy entity - event triggered and generated by the collider system 
//this event is then broadcast and then the requried system then does their thing
//this event is then interperted by the damage taken , the audio output systems and then they decude the health and output the requried autio for this event 


//so the life cycle for this is
//event generated by some system 
//event stored in the event queue for the next frame to 
//next frame 
//the event queue is polled and then broad casted
//the events are then resovled by the systems that look into the events

//since there could be many type of events 
//such as event spawn entity
//event take damage
//there is going to be an abstract event class from which the various events will then inherit
//and when the event is passed to other part of the system after broadcasting

#include"ECS/Entity.h"
#include<memory>

enum eventTypes {
	damageEvent,
	spawnEntityEvent
};

class event
{
public:
	virtual ~event() = default;
	virtual eventTypes getEventType() const = 0;
};

class DamageEvent : public event{
public:
	std::shared_ptr<Entity> damageDealer;
	std::shared_ptr<Entity> damageReciever;
	int damageAmount;

	DamageEvent(const std::shared_ptr<Entity> e1
				, const std::shared_ptr<Entity> e2
				, int damage)
		: damageDealer(e1), damageReciever(e2) , damageAmount(damage) { }

	eventTypes getEventType() const override { return eventTypes::damageEvent; }
};

class SpawnEntityEvent : public event{
public:
	std::string type;	//or the tag for the entity , that is the type of entity that it is whether it is a player or it is a bullet or npc or anything
	vec2 position;

	SpawnEntityEvent(const std::string& type
					, const vec2& position)
		: type(type) , position(position){ }
	eventTypes getEventType() const override { return eventTypes::spawnEntityEvent; }
};